name: Experiment Task
description: Create a task for this experiment
title: "[TASK] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Create a new task to track work on this experiment.

        **Note:** If this experiment uses Linear, this issue will sync automatically. Reference format: `DEVLABS-###`

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: "Describe the task in detail..."
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - Feature Development
        - Bug Fix
        - Documentation
        - Testing
        - Infrastructure
        - Research
        - Refactoring
        - Chore
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Low
        - Medium
        - High
        - Urgent
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will you know this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there other tasks that must be completed first?
      placeholder: "List task IDs or descriptions (e.g., DEVLABS-42, #15)..."

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How complex is this task?
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (4-8 hours)
        - L (1-2 days)
        - XL (> 2 days)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - API
        - UI
        - Infrastructure
        - Documentation
        - Testing
        - Other

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation notes?
      placeholder: "Add technical context, design decisions, or HubSpot services needed..."
